import { 
  Hammer, Droplets, Zap, PaintBucket, Scissors, Ruler, 
  Wind, LayoutGrid, Sparkles, User, Settings, HardHat 
} from 'lucide-react';
import { Category, Worker } from './types';

export const CATEGORIES: Category[] = [
  { id: 'electrician', name: 'Electrician (بجلی)', icon: 'Zap', description: '2.4k+ Workers' },
  { id: 'plumber', name: 'Plumber (پلمبر)', icon: 'Droplets', description: '1.8k+ Workers' },
  { id: 'tailor', name: 'Tailor (درزی)', icon: 'Scissors', description: '3.1k+ Workers' },
  { id: 'carpenter', name: 'Carpenter (بڑھئی)', icon: 'Hammer', description: '1.2k+ Workers' },
  { id: 'painter', name: 'Painter (رنگ ساز)', icon: 'PaintBucket', description: '900+ Workers' },
  { id: 'ac-tech', name: 'AC Tech (اے سی)', icon: 'Wind', description: '1.5k+ Workers' },
  { id: 'tiler', name: 'Tiler (ٹائلر)', icon: 'LayoutGrid', description: '700+ Workers' },
  { id: 'cleaner', name: 'Cleaner (صفائی)', icon: 'Sparkles', description: '1.1k+ Workers' },
];

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'w1',
    name: 'Ahmed Khan',
    category: 'electrician',
    rating: 4.8,
    totalRatings: 124,
    pricePerHour: 500,
    priceRange: '500 - 1200',
    initials: 'AK',
    bgColor: 'teal',
    isVerified: true,
    location: 'Lahore',
    phone: '03001234561',
    description: 'Specialist in home wiring and inverter installation.',
    experience: '10 years',
    completedJobs: 450
  },
  {
    id: 'w2',
    name: 'Saeed Anwar',
    category: 'plumber',
    rating: 4.9,
    totalRatings: 89,
    pricePerHour: 400,
    priceRange: '400 - 1500',
    initials: 'SA',
    bgColor: 'blue',
    isVerified: true,
    location: 'Karachi',
    phone: '03001234562',
    description: 'Expert in modern plumbing systems and leakage detection.',
    experience: '8 years',
    completedJobs: 320
  },
  {
    id: 'w3',
    name: 'Bilal Malik',
    category: 'carpenter',
    rating: 4.7,
    totalRatings: 56,
    pricePerHour: 600,
    priceRange: '600 - 2000',
    initials: 'BM',
    bgColor: 'coral',
    isVerified: false,
    location: 'Rawalpindi',
    phone: '03001234563',
    description: 'Custom furniture design and precision repair work.',
    experience: '5 years',
    completedJobs: 180
  },
  {
    id: 'w4',
    name: 'Zahid Ali',
    category: 'painter',
    rating: 4.6,
    totalRatings: 42,
    pricePerHour: 350,
    priceRange: '350 - 1000',
    initials: 'ZA',
    bgColor: 'purple',
    isVerified: true,
    location: 'Islamabad',
    phone: '03001234564',
    description: 'Professional wall painting and texture specialist.',
    experience: '12 years',
    completedJobs: 510
  },
  {
    id: 'w5',
    name: 'Aslam Pervez',
    category: 'tailor',
    rating: 4.5,
    totalRatings: 210,
    pricePerHour: 800,
    priceRange: '800 - 2500',
    initials: 'AP',
    bgColor: 'orange',
    isVerified: true,
    location: 'Faisalabad',
    phone: '03001234565',
    description: 'Master tailor for traditional and modern wear.',
    experience: '20 years',
    completedJobs: 1200
  },
  {
    id: 'w6',
    name: 'Haris Rauf',
    category: 'ac-tech',
    rating: 4.9,
    totalRatings: 15,
    pricePerHour: 1000,
    priceRange: '1000 - 3000',
    initials: 'HR',
    bgColor: 'teal',
    isVerified: true,
    location: 'Multan',
    description: 'AC installation and gas refilling expert.',
    experience: '4 years',
    completedJobs: 95
  },
  {
    id: 'w7',
    name: 'Kamran Akmal',
    category: 'plumber',
    rating: 4.4,
    totalRatings: 45,
    pricePerHour: 450,
    priceRange: '450 - 1400',
    initials: 'KA',
    bgColor: 'blue',
    isVerified: true,
    location: 'Peshawar',
    description: 'Geyser repair and new pipe fitting specialist.',
    experience: '6 years',
    completedJobs: 210
  },
  {
    id: 'w8',
    name: 'Shoaib Malik',
    category: 'electrician',
    rating: 4.7,
    totalRatings: 156,
    pricePerHour: 550,
    priceRange: '550 - 1800',
    initials: 'SM',
    bgColor: 'purple',
    isVerified: true,
    location: 'Sialkot',
    description: 'Industrial electrician and motor winding expert.',
    experience: '15 years',
    completedJobs: 890
  },
  {
    id: 'w9',
    name: 'Fakhar Zaman',
    category: 'cleaner',
    rating: 4.8,
    totalRatings: 34,
    pricePerHour: 300,
    priceRange: '300 - 900',
    initials: 'FZ',
    bgColor: 'teal',
    isVerified: false,
    location: 'Mardan',
    description: 'Deep cleaning services for offices and homes.',
    experience: '3 years',
    completedJobs: 150
  },
  {
    id: 'w10',
    name: 'Babar Azam',
    category: 'carpenter',
    rating: 5.0,
    totalRatings: 500,
    pricePerHour: 1000,
    priceRange: '1000 - 5000',
    initials: 'BA',
    bgColor: 'coral',
    isVerified: true,
    location: 'Lahore',
    description: 'King of woodcraft and interior detailing.',
    experience: '9 years',
    completedJobs: 1500
  },
  {
    id: 'w11',
    name: 'Naseem Shah',
    category: 'ac-tech',
    rating: 4.6,
    totalRatings: 28,
    pricePerHour: 1200,
    priceRange: '1200 - 3500',
    initials: 'NS',
    bgColor: 'blue',
    isVerified: true,
    location: 'Quetta',
    description: 'Splits and chillers maintenance specialist.',
    experience: '5 years',
    completedJobs: 130
  },
  {
    id: 'w12',
    name: 'Imad Wasim',
    category: 'tiler',
    rating: 4.3,
    totalRatings: 67,
    pricePerHour: 400,
    priceRange: '400 - 1200',
    initials: 'IW',
    bgColor: 'purple',
    isVerified: true,
    location: 'Karachi',
    description: 'Tiles and marble floor installation expert.',
    experience: '11 years',
    completedJobs: 420
  },
  {
    id: 'w13',
    name: 'Shadab Khan',
    category: 'painter',
    rating: 4.9,
    totalRatings: 88,
    pricePerHour: 380,
    priceRange: '380 - 1300',
    initials: 'SK',
    bgColor: 'orange',
    isVerified: true,
    location: 'Islamabad',
    description: 'Creative wall designs and high-gloss finishes.',
    experience: '7 years',
    completedJobs: 280
  },
  {
    id: 'w14',
    name: 'Shaheen Afridi',
    category: 'electrician',
    rating: 4.8,
    totalRatings: 92,
    pricePerHour: 600,
    priceRange: '600 - 2200',
    initials: 'SA',
    bgColor: 'teal',
    isVerified: true,
    location: 'Landi Kotal',
    description: 'Fast and reliable electrical troubleshooting.',
    experience: '6 years',
    completedJobs: 340
  },
  {
    id: 'w15',
    name: 'Mohammad Rizwan',
    category: 'tailor',
    rating: 4.9,
    totalRatings: 450,
    pricePerHour: 900,
    priceRange: '900 - 4000',
    initials: 'MR',
    bgColor: 'blue',
    isVerified: true,
    location: 'Peshawar',
    description: 'Exquisite stitching and bridal wear design.',
    experience: '18 years',
    completedJobs: 2500
  },
  {
    id: 'w16',
    name: 'Iftikhar Ahmed',
    category: 'carpenter',
    rating: 4.5,
    totalRatings: 112,
    pricePerHour: 500,
    priceRange: '500 - 1500',
    initials: 'IA',
    bgColor: 'coral',
    isVerified: true,
    location: 'Abbottabad',
    description: 'Heavy duty wood construction and roofing.',
    experience: '22 years',
    completedJobs: 980
  },
  {
    id: 'w17',
    name: 'Hassan Ali',
    category: 'cleaner',
    rating: 4.6,
    totalRatings: 44,
    pricePerHour: 320,
    priceRange: '320 - 1000',
    initials: 'HA',
    bgColor: 'purple',
    isVerified: true,
    location: 'Gujranwala',
    description: 'Professional carpet and sofa cleaning.',
    experience: '4 years',
    completedJobs: 190
  },
  {
    id: 'w18',
    name: 'Azhar Ali',
    category: 'painter',
    rating: 4.2,
    totalRatings: 55,
    pricePerHour: 300,
    priceRange: '300 - 800',
    initials: 'AA',
    bgColor: 'orange',
    isVerified: false,
    location: 'Lahore',
    description: 'Basic interior and exterior house painting.',
    experience: '13 years',
    completedJobs: 410
  },
  {
    id: 'w19',
    name: 'Sarfaraz Ahmed',
    category: 'plumber',
    rating: 4.7,
    totalRatings: 134,
    pricePerHour: 480,
    priceRange: '480 - 1600',
    initials: 'SA',
    bgColor: 'teal',
    isVerified: true,
    location: 'Karachi',
    description: 'Efficient pipeline management and blockage removal.',
    experience: '14 years',
    completedJobs: 670
  },
  {
    id: 'w20',
    name: 'Usama Mir',
    category: 'ac-tech',
    rating: 4.4,
    totalRatings: 19,
    pricePerHour: 1100,
    priceRange: '1100 - 3200',
    initials: 'UM',
    bgColor: 'blue',
    isVerified: false,
    location: 'Sialkot',
    description: 'Window AC and small appliance repair.',
    experience: '2 years',
    completedJobs: 50
  }
];

